import { SalesData, Trend, Competitor, Campaign, DashboardStats } from "@/types";

// ─── Mock Sales Data ─────────────────────────────────────────────────
export const mockSalesData: SalesData = {
  totalRevenue: 485000,
  totalOrders: 612,
  avgOrderValue: 792,
  conversionRate: 3.4,
  weeklyGrowth: 12.8,
  repeatPurchaseRate: 28,
  abandonedCarts: 847,
  topProducts: [
    { name: "Linen Summer Shirt - White", revenue: 68400, units: 114, growth: 32, category: "men-tops" },
    { name: "Floral Maxi Dress", revenue: 54200, units: 87, growth: 28, category: "women-dresses" },
    { name: "Oversized Linen Pants - Beige", revenue: 47800, units: 96, growth: 19, category: "men-bottoms" },
    { name: "Smart Casual Blazer - Navy", revenue: 38900, units: 62, growth: 15, category: "men-formal" },
    { name: "Summer Co-ord Set - Women", revenue: 35600, units: 58, growth: 41, category: "women-sets" },
  ],
  lowProducts: [
    { name: "Formal Blazer - Navy", revenue: 8200, units: 9, growth: -22, category: "men-formal" },
    { name: "Winter Wool Coat", revenue: 5400, units: 5, growth: -45, category: "women-outerwear" },
    { name: "Leather Belt Set", revenue: 3100, units: 14, growth: -8, category: "accessories" },
  ],
  insights: [],
  revenueByDay: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 86400000).toISOString().split("T")[0],
    revenue: Math.floor(10000 + Math.random() * 25000 + (i > 20 ? 8000 : 0)),
    orders: Math.floor(15 + Math.random() * 35),
  })),
};

// ─── Mock Trends ─────────────────────────────────────────────────────
export const mockTrends: Trend[] = [
  {
    id: "t1",
    name: "Old Money Aesthetic",
    platform: "tiktok",
    trendScore: 88,
    growthRate: 42,
    relevanceScore: 91,
    expectedPeakDays: 18,
    hashtags: ["#oldmoney", "#quietluxury", "#minimalist", "#لوكس"],
    sounds: ["Classical violin remix", "Lo-fi luxury beats"],
    category: "aesthetic",
    description: "Minimal, beige-toned, quiet luxury styling dominating Egyptian TikTok",
  },
  {
    id: "t2",
    name: "Linen Summer Fits",
    platform: "instagram",
    trendScore: 84,
    growthRate: 38,
    relevanceScore: 96,
    expectedPeakDays: 12,
    hashtags: ["#linenshirt", "#summerstyle", "#صيف", "#summer_fits"],
    sounds: [],
    category: "product",
    description: "Linen fabric content seeing massive Instagram saves — high purchase intent signal",
  },
  {
    id: "t3",
    name: "Coastal Granddaughter",
    platform: "tiktok",
    trendScore: 76,
    growthRate: 55,
    relevanceScore: 78,
    expectedPeakDays: 25,
    hashtags: ["#coastal", "#beachstyle", "#northcoast", "#ساحلي"],
    sounds: ["Breezy summer beats"],
    category: "aesthetic",
    description: "Coastal / beach aesthetic aligning perfectly with North Coast summer season",
  },
  {
    id: "t4",
    name: "Co-ord Sets Domination",
    platform: "instagram",
    trendScore: 81,
    growthRate: 29,
    relevanceScore: 89,
    expectedPeakDays: 8,
    hashtags: ["#coordinatedset", "#matchingset", "#طقم", "#ootd"],
    sounds: [],
    category: "style",
    description: "Matching co-ord sets consistently outperforming individual pieces in engagement",
  },
  {
    id: "t5",
    name: "Smart Casual Daily",
    platform: "tiktok",
    trendScore: 72,
    growthRate: 47,
    relevanceScore: 85,
    expectedPeakDays: 35,
    hashtags: ["#casualstyle", "#smartcasual", "#debackers", "#أناقة_مصرية"],
    sounds: ["Chill Egyptian pop", "Lo-fi lifestyle beats"],
    category: "style",
    description: "Premium smart casual styling growing fast among Egyptian men 18–30 — work to weekend versatility",
  },
  {
    id: "t6",
    name: "Soft Girl Pastel",
    platform: "instagram",
    trendScore: 68,
    growthRate: 21,
    relevanceScore: 74,
    expectedPeakDays: 40,
    hashtags: ["#softgirl", "#pastel", "#aesthetic", "#ناعم"],
    sounds: [],
    category: "color",
    description: "Pastel color palettes trending in women's fashion content",
  },
];

// ─── Mock Competitors — Debackers real competitors ───────────────────
export const mockCompetitors: Competitor[] = [
  {
    id: "c1",
    name: "Tie House",
    instagramHandle: "@tiehouse",
    website: "tiehouse.ae",
    snapshot: {
      instagramPosts: 30,
      avgEngagement: 3.8,
      topHashtags: ["#tiehouse", "#mensfashion", "#egypt", "#suits"],
      contentThemes: ["celebrity", "discount", "suits", "mass-market", "men-only"],
      postingFrequency: 7,
      tiktokVideos: 12,
      insights: [
        "2.3M Facebook likes — largest social following in Egyptian men's fashion",
        "Running heavy summer discounts: up to 72% off suits — pure volume play",
        "Celebrity campaign with footballer Mohamed Zidan — mass market positioning",
        "Men ONLY — zero women's offering, leaving 50% of market untouched",
        "No TikTok strategy — missing 18–28 male segment entirely",
      ],
    },
  },
  {
    id: "c2",
    name: "British House",
    instagramHandle: "@british.house.official",
    website: "britishhouse.shop",
    snapshot: {
      instagramPosts: 15,
      avgEngagement: 4.1,
      topHashtags: ["#britishhouse", "#mensstyle", "#shirts", "#linen"],
      contentThemes: ["premium", "craftsmanship", "linen", "corporate", "men-shirts"],
      postingFrequency: 4,
      tiktokVideos: 2,
      insights: [
        "135K Instagram followers — premium but very niche audience",
        "Pushing Belgian Linen SS26 collection at EGP 2,345–3,545 per shirt",
        "Men's shirts ONLY — no full wardrobe, no women's line at all",
        "Stores only in Mivida New Cairo + Sheikh Zayed — limited reach",
        "Virtually no TikTok presence — weak with younger demographic",
      ],
    },
  },
  {
    id: "c3",
    name: "Massimo Dutti Egypt",
    instagramHandle: "@massimodutti",
    website: "massimodutti.com/eg",
    snapshot: {
      instagramPosts: 20,
      avgEngagement: 5.2,
      topHashtags: ["#massimodutti", "#luxury", "#fashion", "#egypt"],
      contentThemes: ["international", "luxury", "editorial", "aspirational"],
      postingFrequency: 5,
      tiktokVideos: 0,
      insights: [
        "International luxury brand — global marketing budget but zero Egyptian cultural connection",
        "Stores only in Citystars Heliopolis + Mall of Egypt — premium mall positioning",
        "Pricing far above Egyptian average — aspirational but not accessible to most",
        "No Arabic content — misses Egyptian audience connection completely",
        "Zero TikTok Egypt strategy — not investing in local platform presence",
      ],
    },
  },
];

// ─── Mock Campaigns ───────────────────────────────────────────────────
export const mockCampaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Cairo Summer Essentials",
    objective: "Drive sales of linen summer collection",
    audience: "Men 22–35, Cairo & Alexandria",
    offer: "Buy 2 linen pieces, get 15% off",
    platforms: ["tiktok", "instagram"],
    contentTypes: ["reel", "tiktok-video"],
    hooks: [
      "الحر ده مش هيوقفك — linen collection الجديدة 🌞",
      "Your summer fits should be this clean ✨",
    ],
    captions: [
      "صيف ٢٠٢٥ استعد ليه بـ linen collection الجديدة 🌿 خامات طبيعية، تحس إنك بارد حتى لو الجو ٤٠ درجة 🔥",
    ],
    cta: "تسوق دلوقتي — رابط في البايو",
    visualDirection: "Outdoor Cairo streets, golden hour light, minimal neutral tones, linen textures close-up",
    estimatedKPIs: { reach: 85000, engagement: 4200, conversions: 180, revenue: 142000 },
    confidenceScore: 88,
    explanation:
      "Recommended because: Linen shirt sales +32% last 14 days · Summer trend score = 84 · Tie House + British House have zero casual linen content · Instagram saves for linen content up 56%",
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    status: "ACTIVE",
  },
  {
    id: "camp-2",
    name: "Co-ord Queen",
    objective: "Capture the co-ord set trend before peak",
    audience: "Women 18–30, Egypt-wide",
    offer: "New arrivals — limited pieces",
    platforms: ["instagram", "tiktok"],
    contentTypes: ["reel", "carousel", "story"],
    hooks: [
      "طقم واحد — ١٠٠ طريقة تلبسيه 👗",
      "The co-ord trend is not leaving anytime soon 💅",
    ],
    captions: [
      "أكتر piece في closet-ك هتلبسيها — co-ord set الجديدة بالألوان اللي هتفرقي بيها في أي مكان ✨",
    ],
    cta: "Shop the collection now",
    visualDirection: "Clean white backgrounds, pastel accents, lifestyle shots in cafes and rooftops",
    estimatedKPIs: { reach: 62000, engagement: 3800, conversions: 145, revenue: 115500 },
    confidenceScore: 81,
    explanation:
      "Recommended because: Women co-ord set sales +41% · Instagram trend score = 81 · Competitors not capitalizing on this format · High save rate on co-ord content",
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    status: "DRAFT",
  },
  {
    id: "camp-3",
    name: "Cairo Smart Casual",
    objective: "Own the premium smart casual story for Egyptian men 18–30",
    audience: "Men 18–30, Cairo professionals and university students",
    offer: "New smart casual collection — work to weekend in one look",
    platforms: ["tiktok", "instagram"],
    contentTypes: ["tiktok-video", "reel", "carousel"],
    hooks: [
      "من الشغل للسهرة بـ look واحد فقط 👔✨",
      "The smart casual era is here — and Debackers owns it",
    ],
    captions: [
      "مش لازم تغير هدومك ١٠ مرات 🙌 smart casual collection الجديدة من Debackers — أنيق في أي مكان، في أي وقت 🇪🇬 — رابط في البايو",
    ],
    cta: "اكتشف الكولكشن — رابط في البايو",
    visualDirection: "Cairo rooftops, cafe terraces, modern office settings — clean neutral tones, confident styling",
    estimatedKPIs: { reach: 120000, engagement: 8500, conversions: 95, revenue: 74100 },
    confidenceScore: 76,
    explanation:
      "Recommended because: Smart casual TikTok content +47% · Casual sets sales +15% · No competitor owns premium smart casual positioning · 18–30 Egyptian men seeking versatile wardrobe",
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    status: "DRAFT",
  },
];

// ─── Mock Dashboard Stats ─────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
  totalRevenue: 485000,
  revenueGrowth: 12.8,
  totalOrders: 612,
  ordersGrowth: 8.4,
  avgOrderValue: 792,
  aovGrowth: 4.1,
  activeCampaigns: 1,
  topTrend: "Old Money Aesthetic",
  trendScore: 88,
};
